/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Manuel Fernando Parra Gonzalez 22550032
 */
public class EspVida extends javax.swing.JFrame {

    /**
     * Creates new form EspVida
     */
    public EspVida() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrpGenero = new javax.swing.ButtonGroup();
        btngFumacion = new javax.swing.ButtonGroup();
        btnSabadrink = new javax.swing.ButtonGroup();
        btngMusculo = new javax.swing.ButtonGroup();
        btngChamba = new javax.swing.ButtonGroup();
        btngEnCronica = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        opcMasc = new javax.swing.JRadioButton();
        opcFem = new javax.swing.JRadioButton();
        btnSig = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        opcSi1 = new javax.swing.JRadioButton();
        opcNo1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        opcSi2 = new javax.swing.JRadioButton();
        opcNo2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        opcCorrer = new javax.swing.JRadioButton();
        opcNadar = new javax.swing.JRadioButton();
        opcBox = new javax.swing.JRadioButton();
        opcNinguno = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        opcOfice = new javax.swing.JRadioButton();
        opcMaistro = new javax.swing.JRadioButton();
        opcPurple = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        txtfEdad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        opcSi3 = new javax.swing.JRadioButton();
        opcNo3 = new javax.swing.JRadioButton();
        txtfProm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtfAprox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Selecciona tu genero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 30));

        GrpGenero.add(opcMasc);
        opcMasc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcMasc.setText("Masculino");
        opcMasc.setToolTipText("");
        getContentPane().add(opcMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        GrpGenero.add(opcFem);
        opcFem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcFem.setText("Femenino");
        getContentPane().add(opcFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        btnSig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSig.setText("Aceptar");
        btnSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSigMouseClicked(evt);
            }
        });
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });
        getContentPane().add(btnSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("¿Eres fumador?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btngFumacion.add(opcSi1);
        opcSi1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcSi1.setText("Si");
        getContentPane().add(opcSi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        btngFumacion.add(opcNo1);
        opcNo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcNo1.setText("No");
        getContentPane().add(opcNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("¿Bebes bebidas alcoholicas?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        btnSabadrink.add(opcSi2);
        opcSi2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcSi2.setText("Si");
        getContentPane().add(opcSi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnSabadrink.add(opcNo2);
        opcNo2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcNo2.setText("No");
        getContentPane().add(opcNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("¿Practicas algun deporte?¿Cual?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btngMusculo.add(opcCorrer);
        opcCorrer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcCorrer.setText("Correr");
        opcCorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcCorrerActionPerformed(evt);
            }
        });
        getContentPane().add(opcCorrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btngMusculo.add(opcNadar);
        opcNadar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcNadar.setText("Nadar");
        getContentPane().add(opcNadar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        btngMusculo.add(opcBox);
        opcBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcBox.setText("Boxeo");
        getContentPane().add(opcBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        btngMusculo.add(opcNinguno);
        opcNinguno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcNinguno.setText("Ninguno");
        opcNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNingunoActionPerformed(evt);
            }
        });
        getContentPane().add(opcNinguno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de trabajo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        btngChamba.add(opcOfice);
        opcOfice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcOfice.setText("Oficina");
        opcOfice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcOficeActionPerformed(evt);
            }
        });
        getContentPane().add(opcOfice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        btngChamba.add(opcMaistro);
        opcMaistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcMaistro.setText("Maestro");
        getContentPane().add(opcMaistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        btngChamba.add(opcPurple);
        opcPurple.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcPurple.setText("Seguridad(Guardia, Policia, etc)");
        getContentPane().add(opcPurple, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Selecciona la opcion que mas le convenga");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        txtfEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfEdadActionPerformed(evt);
            }
        });
        getContentPane().add(txtfEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ingrese su edad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("¿Tiene alguna enfermedad cronica?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        btngEnCronica.add(opcSi3);
        opcSi3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcSi3.setText("Si");
        getContentPane().add(opcSi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btngEnCronica.add(opcNo3);
        opcNo3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opcNo3.setText("No");
        getContentPane().add(opcNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        txtfProm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtfProm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Promedio esperado de vida");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Fecha aproximada de deceso");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        txtfAprox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfAprox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAproxActionPerformed(evt);
            }
        });
        getContentPane().add(txtfAprox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSigActionPerformed

    private void opcCorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcCorrerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcCorrerActionPerformed

    private void opcNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcNingunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcNingunoActionPerformed

    private void opcOficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcOficeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcOficeActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void txtfEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfEdadActionPerformed
        // TODO add your handling code here:
        txtfEdad.setText(null);
        
    }//GEN-LAST:event_txtfEdadActionPerformed

    private void btnSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSigMouseClicked
        // TODO add your handling code here:
        int Aprox,Promedio, Edad, Genero = 0, Fumacion = 0, Juebebes = 0, Musculo = 0, Cronica = 0, Chamba = 0;
        
        Edad=Integer.parseInt(txtfEdad.getText());
        
        
        if(opcMasc.isSelected()){
            Genero = -3;
        }else if(opcFem.isSelected()){
            Genero = 3;
        }
        
        if(opcSi1.isSelected()){
            Fumacion = -5;
        }else if(opcNo1.isSelected()){
            Fumacion = 2;
        }
        
        if(opcSi2.isSelected()){
            Juebebes = -6;
        }else if(opcNo2.isSelected()){
            Juebebes = 2;
        }
        
        if(opcCorrer.isSelected()){
            Musculo = 3;
        }else if(opcNadar.isSelected()){
            Musculo = 5;
        }else if(opcBox.isSelected()){
            Musculo = -6;
        }else if(opcNinguno.isSelected()){
            Musculo = -3;
        }
        
        if(opcOfice.isSelected()){
            Chamba = -3;
        }else if(opcMaistro.isSelected()){
            Chamba = 2;
        }else if(opcPurple.isSelected()){
            Chamba = -4;
        }
        
        if(opcSi3.isSelected()){
            Cronica = -4;
        }else if(opcNo3.isSelected()){
            Cronica = 2;
        }
        
        Promedio = 75 + Genero + Fumacion + Juebebes + Musculo + Cronica + Chamba;
        Aprox = Promedio - Edad;
        
        txtfProm.setText(String.valueOf(Promedio));
        txtfAprox.setText(String.valueOf("En "+ Aprox + " Años"));
    }//GEN-LAST:event_btnSigMouseClicked

    private void txtfAproxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAproxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAproxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspVida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspVida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrpGenero;
    private javax.swing.ButtonGroup btnSabadrink;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSig;
    private javax.swing.ButtonGroup btngChamba;
    private javax.swing.ButtonGroup btngEnCronica;
    private javax.swing.ButtonGroup btngFumacion;
    private javax.swing.ButtonGroup btngMusculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton opcBox;
    private javax.swing.JRadioButton opcCorrer;
    private javax.swing.JRadioButton opcFem;
    private javax.swing.JRadioButton opcMaistro;
    private javax.swing.JRadioButton opcMasc;
    private javax.swing.JRadioButton opcNadar;
    private javax.swing.JRadioButton opcNinguno;
    private javax.swing.JRadioButton opcNo1;
    private javax.swing.JRadioButton opcNo2;
    private javax.swing.JRadioButton opcNo3;
    private javax.swing.JRadioButton opcOfice;
    private javax.swing.JRadioButton opcPurple;
    private javax.swing.JRadioButton opcSi1;
    private javax.swing.JRadioButton opcSi2;
    private javax.swing.JRadioButton opcSi3;
    private javax.swing.JTextField txtfAprox;
    private javax.swing.JTextField txtfEdad;
    private javax.swing.JTextField txtfProm;
    // End of variables declaration//GEN-END:variables
}
